version: "3"

services:
  cean-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 5400
    image: kbespalyi/cean-api-server
    environment:
      - NODE_ENV=production
      - PORT=5400
    ports:
      - "127.0.0.1:5400:5400"
    expose:
      - "5400"
    links:
      - couchbase
    networks:
      - front-tier
      - back-tier
    depends_on:
      - couchbase

  couchbase:
    image: couchbase
    volumes:
      - "db-data:/var/lib/couchbase/data"
    environment:
      - CLUSTER=localhost
      - PORT=8091
      - MEMORY_QUOTA=25
      - INDEX_MEMORY_QUOTA=256
      - FTS_MEMORY_QUOTA=256
      - SERVICES="kv,n1ql,index,fts"
      - RAMSIZEMB=512
      - RAMSIZEINDEXMB=256
      - RAMSIZEFTSMB=256
      - BUCKETS=default
      - BUCKETSIZES=256
      - AUTOREBALANCE=true
    deploy:
      replicas: 1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    networks:
      - back-tier

  website:
    image: php:apache
    volumes:
      - ./frontend/dist:/var/www/html
    ports:
      - "127.0.0.1:80:80"
    expose:
      - "80"
    environment:
      - apiUrl=http://cean-service:5400
      - NODE_ENV=production
    links:
      - cean-service
    networks:
      - front-tier
      - back-tier
    depends_on:
      - cean-service

volumes:
  db-data:

networks:
  front-tier:
  back-tier:

#  clean:
#    extends:
#      service: staging
#    command: rm -rf node_modules
#  install:
#    extends:
#      service: staging
#    command: npm install --silent
