version: 2
jobs:
  build:
    working_directory: ~/cean-server
    docker:
      - image: circleci/node:9.1.0
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      #- run:
      #    name: Update npm
      #    command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache- # used if checksum fails
      - run:
          name: "Docker install"
          command: |
            sudo curl -L -o /usr/bin/docker 'https://s3-external-1.amazonaws.com/circle-downloads/docker-1.9.1-circleci'
            sudo chmod 0755 /usr/bin/docker
      - run:
          name: "Starting docker"
          command: |
            docker info >/dev/null 2>&1 || service docker start
      - run:
          name: "Starting couchbase"
          command: |
            docker pull mdavidallen/couchbase:latest
            docker run -d --name hosdock -p 8090-8099:8090-8099 -p 9110:9110 -p 11210:11210 -p 18091:18091 -p 18092:18092 mdavidallen/couchbase:latest
            sleep 20
            curl --retry 20 --retry-delay 10 -v http://172.19.0.2:8091/pools/default/buckets -C -
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results
          destination: test-results/junit
